<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="RAHUL-JACOB" failures="1" tests="3" name="Test" time="11.91" errors="0" timestamp="2024-02-12T11:04:42 IST">
  <testcase classname="testscripts.ManageOfferCodeTest" name="verifyWhetherTheUserIsAbleToAddANewOfferCodeInTheManageOfferCodePage" time="2.579">
    <skipped/>
  </testcase> <!-- verifyWhetherTheUserIsAbleToAddANewOfferCodeInTheManageOfferCodePage -->
  <testcase classname="testscripts.ManageOfferCodeTest" name="verifyWhetherTheUserIsAbleToAddANewOfferCodeInTheManageOfferCodePage" time="2.167">
    <skipped/>
  </testcase> <!-- verifyWhetherTheUserIsAbleToAddANewOfferCodeInTheManageOfferCodePage -->
  <testcase classname="testscripts.ManageOfferCodeTest" name="verifyWhetherTheUserIsAbleToAddANewOfferCodeInTheManageOfferCodePage" time="1.954">
    <failure type="java.lang.AssertionError" message="User is not able to add a new promo code in the manage offer code page expected [×
Alert!
Offer Code already exists.] but found [×
Alert!
Offer Created Successfully]">
      <![CDATA[java.lang.AssertionError: User is not able to add a new promo code in the manage offer code page expected [×
Alert!
Offer Code already exists.] but found [×
Alert!
Offer Created Successfully]
at testscripts.ManageOfferCodeTest.verifyWhetherTheUserIsAbleToAddANewOfferCodeInTheManageOfferCodePage(ManageOfferCodeTest.java:51)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 30 stack frames]]>
    </failure>
  </testcase> <!-- verifyWhetherTheUserIsAbleToAddANewOfferCodeInTheManageOfferCodePage -->
</testsuite> <!-- Test -->
